version: '2'
services:
  booklib-app:
    image: docker.io/bsdockerzg/booklib:latest
    command: export PORT=8080
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://booklib-postgresql:5432/booklib
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - ${PORT}:8080
  booklib-postgresql:
    extends:
      file: src/main/docker/postgresql.yml
      service: booklib-postgresql
  kafka:
    extends:
      file: src/main/docker/kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: src/main/docker/kafka.yml
      service: zookeeper
