version: '2'
services:
  booklib-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/booklib/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=booklib
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432
